name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      if: hashFiles('setup.py')
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      if: hashFiles('setup.py')
      run: |
        pip install -e '.[test]'
    - name: Run tests
      if: hashFiles('setup.py')
      run: |
        pytest
